// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Antares.Service.MarketProfile.LykkeClient.Models
{
    /// <summary>
    /// Defines values for ErrorCode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorCode
    {
        [EnumMember(Value = "InvalidInput")]
        InvalidInput,
        [EnumMember(Value = "RuntimeProblem")]
        RuntimeProblem,
        [EnumMember(Value = "PairNotFound")]
        PairNotFound
    }
}
