// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.MarketProfile.Client.Models
{
    using Lykke.Service;
    using Lykke.Service.MarketProfile;
    using Lykke.Service.MarketProfile.Client;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for ErrorCode.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ErrorCode
    {
        [EnumMember(Value = "InvalidInput")]
        InvalidInput,
        [EnumMember(Value = "RuntimeProblem")]
        RuntimeProblem,
        [EnumMember(Value = "PairNotFound")]
        PairNotFound
    }
}
