// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace Antares.Service.MarketProfile.LykkeClient.Models
{
    public partial class ErrorModel
    {
        /// <summary>
        /// Initializes a new instance of the ErrorModel class.
        /// </summary>
        public ErrorModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ErrorModel class.
        /// </summary>
        /// <param name="code">Possible values include: 'InvalidInput',
        /// 'RuntimeProblem', 'PairNotFound'</param>
        public ErrorModel(ErrorCode? code = default(ErrorCode?), string message = default(string))
        {
            Code = code;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'InvalidInput',
        /// 'RuntimeProblem', 'PairNotFound'
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public ErrorCode? Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
